### ISSUE TITLE
如何不打印报错信息

### ISSUE THREAD

**Issue by pythonla** [dongrixinyu/JioNLP#181]
2024-01-24 17:13:55 ERROR parse_time_period: Traceback (most recent call last):
  File "C:\Users\YZS\miniconda3\lib\site-packages\jionlp\gadget\time_parser.py", line 1209, in parse_time_period
    first_full_time_handler, second_full_time_handler, _, blur_time = self.parse_time_span_point(
  File "C:\Users\YZS\miniconda3\lib\site-packages\jionlp\gadget\time_parser.py", line 1048, in parse_time_span_point
    blur_time = self.parse_time_point(
  File "C:\Users\YZS\miniconda3\lib\site-packages\jionlp\gadget\time_parser.py", line 1526, in parse_time_point
    raise ValueError('## exception string `{}`.'.format(time_string))
ValueError: ## exception string `1`.

首先感谢大佬的工具。
已经使用jio.ner.extract_time抽取出时间实体，然后jio.parse_time时还是报错，请问如何忽略这些报错，不在终端输出，感谢！

**Comment by dongrixinyu** [comment]
这种你自己 try catch 一下，然后取消打印，后续打算去掉日志功能

**Comment by pythonla** [comment]
这是来自QQ邮箱的假期自动回复邮件。你发给我的信件已经收到。谢谢!
