### ISSUE TITLE
输入"明天下午一点参加下半年销售大会 " 提示ValueError: the string `明天下午一点参加下半年销售大会。` is illegal, because the hour-min-sec stringcan NOT be designated to a specific day.

### ISSUE THREAD

**Issue by jiangxia207** [dongrixinyu/JioNLP#227]
**提问题时，请尊重我！把必要的信息，什么环境，输入具体什么文本，运行什么函数讲清楚！**
**不要甩一句话，说的不清不楚，我无从定位，浪费时间。这样的提单我将直接close。**

**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本:  3.10.12
- jionlp 版本:  1.5.14

2. jionlp的调用代码与输入文本(Code & Text):
```
print(jio.parse_time(sys.argv[1], time_base=time.time()))

3. 调用报错日志如下(Log):
```
Traceback (most recent call last):
  File "/opt/fenmiaoReport_dev/timepy.py", line 12, in <module>
    main()
  File "/opt/fenmiaoReport_dev/timepy.py", line 7, in main
    print(jio.parse_time(sys.argv[1], time_base=time.time()))
  File "/usr/local/lib/python3.10/dist-packages/jionlp/gadget/time_parser.py", line 809, in __call__
    self.parse_time_span_point(time_string)
  File "/usr/local/lib/python3.10/dist-packages/jionlp/gadget/time_parser.py", line 1071, in parse_time_span_point
    blur_time = self.parse_time_point(
  File "/usr/local/lib/python3.10/dist-packages/jionlp/gadget/time_parser.py", line 1610, in parse_time_point
    raise ValueError('the string `{}` is illegal, because the hour-min-sec string'
ValueError: the string `今天下午参加下半年销售大会。` is illegal, because the hour-min-sec stringcan NOT be designated to a specific day.
```


**期望行为(Expectation)**

> 返回明天下午一点

**Comment by dongrixinyu** [comment]
使用应该是有问题。里面有两个时间字符串。最好先过一遍大模型，然后用工具包做准确解析：
