### ISSUE TITLE
[BUG] `jio.parse_money("小于40万")` 报错

### ISSUE THREAD

**Issue by LucienShui** [dongrixinyu/JioNLP#240]
# 环境

```
python==3.11.9
jionlp==1.5.15
```

# 复现

```
import jionlp as jio
print(jio.parse_money("小于40万"))
```

```shell
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print(jio.parse_money("小于40万"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/jionlp/gadget/money_parser.py", line 604, in __call__
    return self.parse_single_money(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "python3.11/site-packages/jionlp/gadget/money_parser.py", line 673, in parse_single_money
    raise ValueError(self.type_error.format(money_string))
ValueError: the given money_string `小于40万` is illegal.
```

**Comment by dongrixinyu** [comment]
修复了
