### ISSUE TITLE
“上(下)季度"查询异常

### ISSUE THREAD

**Issue by Payne214** [dongrixinyu/JioNLP#25]
ValueError: The given time string `上季度` is illegal.

**Comment by dongrixinyu** [comment]
fixed

**Comment by Payne214** [comment]
import jionlp as jio
result = jio.parse_time("上季度")
print(result)

Traceback (most recent call last):
  File "F:/jio_start.py", line 8, in <module>
    result = jio.parse_time("上季度")
  File "D:\ProgramData\Miniconda3\envs\py38\lib\site-packages\jionlp\gadget\time_parser.py", line 650, in __call__
    self.parse_time_span_point(time_string)
  File "D:\ProgramData\Miniconda3\envs\py38\lib\site-packages\jionlp\gadget\time_parser.py", line 717, in parse_time_span_point
    blur_time = self.parse_time_point(
  File "D:\ProgramData\Miniconda3\envs\py38\lib\site-packages\jionlp\gadget\time_parser.py", line 1171, in parse_time_point
    raise ValueError('can not parse the string `{}`.'.format(time_string))
ValueError: can not parse the string `上季度`.

**Comment by dongrixinyu** [comment]
`jio.parse_time('上季度')`
# {'type': 'time_span', 'definition': 'accurate', 'time': ['2021-04-01 00:00:00', '2021-06-30 23:59:59']}

**Comment by Payne214** [comment]
重新安装JioNLP，可以了
非常感谢！
