### ISSUE TITLE
新闻地名识别本地无法正常运行

### ISSUE THREAD

**Issue by githen-cn** [dongrixinyu/JioNLP#36]
1. jionlp版本(Version): `1.3.39` 
1. 调用报错日志如下(Log):
```
➜  JioNLP git:(master) ✗ python3.9 index.py
`jio.help()` is provided to search how to use jio functions.
Traceback (most recent call last):
  File "python/JioNLP/index.py", line 6, in <module>
    print(jio.recognize_location(text))
  File "python/JioNLP/jionlp/gadget/location_recognizer.py", line 381, in __call__
    self._prepare()
  File "python/JioNLP/jionlp/gadget/location_recognizer.py", line 111, in _prepare
    self.pkuseg = pkuseg.pkuseg(postag=True)
TypeError: __init__() got an unexpected keyword argument 'postag'
```
1. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
text = '海洋一号D星。中新网北京6月11日电(郭超凯)记者从中国国家航天局获悉，6月11日2时31分，在牛家村，中国在太原卫星发射中心用长征二号丙运载火箭成功发射海洋一号D星。该星将与海洋一号C星组成中国首个海洋民用业务卫星星座。相比于美国，海洋一号D星是中国第四颗海洋水色系列卫星，是国家民用空间基础设施规划的首批海洋业务卫星之一。'
res = jio.recognize_location(text)
print(res)
```

**期望行为(Expect)**

> 可以和样例运行出一样的结果

**Comment by dongrixinyu** [comment]
- 建议从 github 上手动安装 pkuseg 0.0.25 版本。或者 pip list | grep pkuseg 查看是不是 0.0.25版，如果不是说明有问题。
    - 我看了一下，原因可能是 python 3.9版本某些函数改变了，导致pkuseg 装不上。也有可能是pkuseg 自己不知道瞎操作了什么，导致你pip 安装会出版本问题。

- 由于分词和词性pkuseg 做的也是挺垃圾的，后续我会在包内自己做一个。

**Comment by dongrixinyu** [comment]
如果不行，就把py 退回 3.8 再安装pkuseg 的 0.0.25版本

**Comment by githen-cn** [comment]
py修改为3.7的正常运行了
