### ISSUE TITLE
Exception: Http请求失败，状态码：403，错误信息： {"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}

### ISSUE THREAD

**Issue by fresh382227905** [dongrixinyu/JioNLP#5]
使用讯飞api时处理多条数据生成时出现：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/back_translation.py", line 164, in iter_api_by_language
    tmp = mt_api(text, from_lang=chinese_lang, to_lang=foreign_lang)
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 43, in wrapper
    f = func(self, *args, **kargs)
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 53, in wrapper
    f = func(self, *args, **kargs)
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 89, in wrapper
    raise Exception(err)
Exception: Http请求失败，状态码：403，错误信息：
{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}
2020-10-09 13:48:27 ERROR wrapper: Http请求失败，状态码：403，错误信息：
{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}
Traceback (most recent call last):
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 70, in wrapper
    f = func(self, *args, **kargs)
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 670, in __call__
    raise Exception(exception_string)
Exception: Http请求失败，状态码：403，错误信息：
{"message":"HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication"}

**Comment by dongrixinyu** [comment]
这个错误是验证码不通过，也就是apikey有问题。你可以自己上讯飞的机器翻译网站上 申请一个自己的账号，有免费额度。

另外，讯飞的接口就是，免费调佣次数少，准确度也不高。可以不用讯飞的 api，换用别的。

**Comment by fresh382227905** [comment]
好呢 谢谢博主




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冬日新雨"<notifications@github.com&gt;; 
发送时间: 2020年10月10日(星期六) 晚上10:50
收件人: "dongrixinyu/JioNLP"<JioNLP@noreply.github.com&gt;; 
抄送: "LMF"<382227905@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dongrixinyu/JioNLP] Exception: Http请求失败，状态码：403，错误信息： {&quot;message&quot;:&quot;HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication&quot;} (#5)





 
这个错误是验证码不通过，也就是apikey有问题。你可以自己上讯飞的机器翻译网站上 申请一个自己的账号，有免费额度。
 
另外，讯飞的接口就是，免费调佣次数少，准确度也不高。可以不用讯飞的 api，换用别的。

**Comment by fresh382227905** [comment]
再请教博主一下哈
使用Tencent_APi时，
tencent_api = jio.TencentApi(
        [{"project_id": "0",
            "secret_id": "AKID84nJhqaLJm0xeHjWYQ4RoX",    ## 这是我把我申请的API修改后错误的 API，非真
            "secret_key": "cxhATebS9svtc4GKAtPvJUh3C"}])###这是错误的密匙

报：
2020-10-15 15:57:45 ERROR wrapper: 'TargetText'
Traceback (most recent call last):
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 70, in wrapper
    f = func(self, *args, **kargs)
  File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 478, in __call__
    return response_json['Response']['TargetText']
KeyError: 'TargetText'
这个错。
然后我去腾讯官网看我的API并没有调用

**Comment by dongrixinyu** [comment]
> 再请教博主一下哈
> 使用Tencent_APi时，
> tencent_api = jio.TencentApi(
> [{"project_id": "0",
> "secret_id": "AKID84nJhqaLJm0xeHjWYQ4RoX", ## 这是我把我申请的API修改后错误的 API，非真
> "secret_key": "cxhATebS9svtc4GKAtPvJUh3C"}])###这是错误的密匙
> 
> 报：
> 2020-10-15 15:57:45 ERROR wrapper: 'TargetText'
> Traceback (most recent call last):
> File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 70, in wrapper
> f = func(self, *args, **kargs)
> File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 478, in **call**
> return response_json['Response']['TargetText']
> KeyError: 'TargetText'
> 这个错。
> 然后我去腾讯官网看我的API并没有调用

我试了一下，这里的问题，还是，你要按照腾讯规定的参数区请求。
你的问题是，你传了一个密钥 dict，但是密钥是错的，就报错了。把密钥改对了就可以 了。
若你一直在传错误的密钥，它会有一个针对多种语言的重复请求，所以就会看到重复报了好几次错误。

执行这个查看接口文档说明。
```
print(jio.TencentApi.__doc__)
```

文档里的  api密钥 dict 是我自己的，可以用。不过你还是自己申请一个，因为我的密钥已经用差不多了。

**Comment by fresh382227905** [comment]
好呢，明白啦。
只是我用的是自己申请的密钥，得到的id和key然后报的这个错误，但显示并没有调用成功，可能是我申请的密匙不对？我到时仔细看下接口文档说明
感谢博主




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冬日新雨"<notifications@github.com&gt;; 
发送时间: 2020年10月16日(星期五) 下午4:19
收件人: "dongrixinyu/JioNLP"<JioNLP@noreply.github.com&gt;; 
抄送: "LMF"<382227905@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dongrixinyu/JioNLP] Exception: Http请求失败，状态码：403，错误信息： {&quot;message&quot;:&quot;HMAC signature cannot be verified, a valid date or x-date header is required for HMAC Authentication&quot;} (#5)





  
再请教博主一下哈
 使用Tencent_APi时，
 tencent_api = jio.TencentApi(
 [{"project_id": "0",
 "secret_id": "AKID84nJhqaLJm0xeHjWYQ4RoX", ## 这是我把我申请的API修改后错误的 API，非真
 "secret_key": "cxhATebS9svtc4GKAtPvJUh3C"}])###这是错误的密匙
 
报：
 2020-10-15 15:57:45 ERROR wrapper: 'TargetText'
 Traceback (most recent call last):
 File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 70, in wrapper
 f = func(self, *args, **kargs)
 File "/home/lmf/anaconda3/envs/tf/lib/python3.7/site-packages/jionlp/gadget/back_translation/translation_api.py", line 478, in call
 return response_json['Response']['TargetText']
 KeyError: 'TargetText'
 这个错。
 然后我去腾讯官网看我的API并没有调用
  
我试了一下，这里的问题，还是，你要按照腾讯规定的参数区请求。
 你的问题是，你传了一个密钥 dict，但是密钥是错的，就报错了。把密钥改对了就可以 了。
 若你一直在传错误的密钥，它会有一个针对多种语言的重复请求，所以就会看到重复报了好几次错误。
 
执行这个查看接口文档说明。
 print(jio.TencentApi.__doc__)  
文档里的  api密钥 dict 是我自己的，可以用。不过你还是自己申请一个，因为我的密钥已经用差不多了。
