### ISSUE TITLE
local variable 'time_string_flag' referenced before assignment

### ISSUE THREAD

**Issue by hesoyam001** [dongrixinyu/JioNLP#61]
res = jio.parse_time('下午三点',ret_future=True)
期望返回明日三点

报错
 jiojio - Failed to load C funcs, use py func instead.
Traceback (most recent call last):
  File "/Users/aaa/PycharmProjects/20220310/32.py", line 5, in <module>
    res = jio.parse_time('下午三点',ret_future=True)
  File "/Users/aaa/venv/20220310/lib/python3.8/site-packages/jionlp/gadget/time_parser.py", line 834, in __call__
    self.parse_time_span_point(time_string)
  File "/Users/aaa/venv/20220310/lib/python3.8/site-packages/jionlp/gadget/time_parser.py", line 1045, in parse_time_span_point
    future_time_string = self._adjust_underlying_future_time(time_string)
  File "/Users/aaa/venv/20220310/lib/python3.8/site-packages/jionlp/gadget/time_parser.py", line 952, in _adjust_underlying_future_time
    if time_string_flag:
UnboundLocalError: local variable 'time_string_flag' referenced before assignment

另请问：C funcs从哪里获取呢

**Comment by hesoyam001** [comment]
尝试自行添加 time_string_flag=True或False，不报错了，但是ret_future不起作用

**Comment by dongrixinyu** [comment]
已修复、C func 是针对 jiojio 的
