### ISSUE TITLE
时间2022 11 23以空格分隔无法解析

### ISSUE THREAD

**Issue by 6DDUU6** [dongrixinyu/JioNLP#94]
**描述(Description)**

> 描述你遇到了什么问题(Please describe your issue here)

1. 版本(Version):
- python 版本: 3.8.0
- jionlp 版本: 1.4.25

2. jionlp的调用代码与输入文本(Code & Text):
```
import jionlp as jio
res = jio.parse_time('2022 11 23')
print(res)
```

3. 调用报错日志如下(Log):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\jionlp\gadget\time_parser.py", line 850, in __call__
    self.parse_time_span_point(time_string)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\jionlp\gadget\time_parser.py", line 1078, in parse_time_span_point
    blur_time = self.parse_time_point(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\jionlp\gadget\time_parser.py", line 1728, in parse_time_point
    raise ValueError('## exception string `{}`.'.format(time_string))
ValueError: ## exception string `2022 11 23`.
```

**期望行为(Expectation)**

> 若返回结果不理想，描述你期望发生的事情(Please describe your expectation)

**请顺手 star 一下右上角的⭐小星星**

**Comment by dongrixinyu** [comment]
已修复
